Fix a couple of problems indicated by compiler warnings
Kenix3/libultraship pull request #127
Opened 2023-02-21 14:01 UTC by nngeorgiy

This PR dramatically reduces the number of warnings introduced by `libultraship` while building `shipwright` for Ubuntu 22.04/amd64. By 'dramatically' I mean that the error log is down from 13MB to 3MB, with most warnings due to conflicting definitions in `libultra/hardware.h`, a file that wasn't even in the original SDK. While I was at it, I also fixed at least four extremely minor bugs. Cheers!

2023-02-23 03:58 UTC, Kenix3 commented on include/libultraship/libultra/hardware.h
> +/* TODO: This file isn't a part of the original SDK headers, so either remove
`hardware.h` should probably just be removed

2023-02-23 03:59 UTC, Kenix3 requested changes
`hardware.h` should probably just be removed

2023-02-23 14:42 UTC, dcvz approved these changes

2023-02-24 03:02 UTC, Kenix3 approved these changes

2023-02-24 03:23 UTC, merged