Declutter logs
Kenix3/libultraship pull request #166
Opened 2023-04-14 05:03 UTC by stratomaster64

Changes the default for release builds to `debug` rather than `trace` through `spdlog`. This should drastically reduce the size of files and allow for easier client-side debugging.

2023-04-14 14:21 UTC, briaguya-ai requested changes
this will make it so we don't have trace logs when building in debug either, we need conditional logic

2023-04-14 14:23 UTC, briaguya-ai commented on src/CMakeLists.txt
> +        SPDLOG_ACTIVE_LEVEL=1
```suggestion
        $<$<CONFIG:Debug>:SPDLOG_ACTIVE_LEVEL=0>
        $<$<NOT:$<CONFIG:Debug>>:SPDLOG_ACTIVE_LEVEL=1>
```

2023-04-15 05:40 UTC, Kenix3 requested changes

2023-04-15 05:40 UTC, Kenix3 commented on src/core/Window.cpp
> +        fileSink->set_level(spdlog::level::debug);
Should ifdef here for `_DEBUG`. If it's `_DEBUG`, allow `trace` level, otherwise `debug` level.

2023-04-15 05:40 UTC, Kenix3 commented on src/core/Window.cpp
> +        GetLogger()->set_level(spdlog::level::debug);
Should ifdef here for `_DEBUG`. If it's `_DEBUG`, allow `trace` level, otherwise `debug` level.

2023-04-15 18:17 UTC, Kenix3 approved these changes

2023-04-15 18:17 UTC, merged