[Feature] Add API for speech synthesis
Kenix3/libultraship pull request #44
Opened 2022-11-22 13:38 UTC by dcvz

2022-11-22 23:57 UTC, Kenix3 requested changes
Only other comment is that we use `h` instead of `hpp`. We definitely don't want the bridge to be `hpp`.

2022-11-22 23:57 UTC, Kenix3 commented on src/speechsynthesizer/DarwinSpeechSynthesizer.hpp
> +    void *mSynthesizer;
```suggestion
    void* mSynthesizer;
```

2022-11-23 05:05 UTC, dcvz commented on src/speechsynthesizer/DarwinSpeechSynthesizer.hpp
> +    void *mSynthesizer;
This was changed by clang tidy as far as I remember.

2022-11-23 06:11 UTC, Kenix3 commented on src/speechsynthesizer/DarwinSpeechSynthesizer.hpp
> +    void *mSynthesizer;
It really should have failed the clang-format test actually.

2022-11-23 10:30 UTC, dcvz commented on src/speechsynthesizer/DarwinSpeechSynthesizer.hpp
> +    void *mSynthesizer;
might be because of the hpp and h. it might only check .h files? renaming them now.

2022-11-23 10:41 UTC, dcvz commented on src/speechsynthesizer/DarwinSpeechSynthesizer.hpp
> +    void *mSynthesizer;
yup, that was it! it now catches things in the h files

2022-11-23 18:39 UTC, Kenix3 reviewed
I'm a little nervous that there is no Linux synthesizer, but I'm not sure if it needs to hold up this PR either.

2022-11-23 19:03 UTC, merged