Libultra implementations
Kenix3/libultraship pull request #493
Opened 2024-04-19 09:40 UTC by KiritoDv

2024-04-21 23:33 UTC, Kenix3 commented
The strategy for handling libultra implementations will be changed in version 2.0.0 of this software. Going to close this for now until there is a good place to PR these.

2024-04-28 19:58 UTC, briaguya-ai commented on src/controller/controldevice/controller/Controller.cpp
> +}
this will return true if any mapping exists for for a controller, even if the mapping is to a physical device that is disconnected

2024-04-28 20:08 UTC, briaguya-ai requested changes
the controller/controldeck side of this should be a separate PR. it is not part of the libultra implementation and it the logic in those changes is broken in this PR

2024-05-07 00:38 UTC, Kenix3 approved these changes

2024-05-07 01:11 UTC, merged